#!/usr/bin/env bash
# One-time (or recovery) host bootstrap for deploying https://github.com/Pratanu123/blog
# Run as root on the target Ubuntu server.
set -euo pipefail

APP_DIR="${APP_DIR:-/opt/blog}"
REPO_URL="${REPO_URL:-https://github.com/Pratanu123/blog.git}"
BRANCH="${DEPLOY_BRANCH:-main}"
PUBLIC_URL="${PUBLIC_URL:-}"

if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root (or with sudo)."
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive

echo "==> Installing Docker, Git, curl, OpenSSH"
apt-get update -y
apt-get install -y ca-certificates curl git openssh-server

if ! command -v docker >/dev/null 2>&1; then
  curl -fsSL https://get.docker.com | sh
fi

systemctl enable --now docker
systemctl enable --now ssh || systemctl enable --now sshd

if [ -z "$PUBLIC_URL" ]; then
  IPV4="$(curl -4 -fsS ifconfig.me || true)"
  if [ -n "$IPV4" ]; then
    PUBLIC_URL="http://${IPV4}"
  else
    PUBLIC_URL="http://localhost"
  fi
fi

HOST_NO_SCHEME="${PUBLIC_URL#http://}"
HOST_NO_SCHEME="${HOST_NO_SCHEME#https://}"
HOST_NO_SCHEME="${HOST_NO_SCHEME%%/*}"

echo "==> Cloning repository into $APP_DIR"
mkdir -p "$(dirname "$APP_DIR")"
if [ ! -d "$APP_DIR/.git" ]; then
  git clone --branch "$BRANCH" "$REPO_URL" "$APP_DIR"
else
  git -C "$APP_DIR" fetch origin "$BRANCH"
  git -C "$APP_DIR" checkout "$BRANCH"
  git -C "$APP_DIR" reset --hard "origin/$BRANCH"
fi

cd "$APP_DIR"
chmod +x scripts/deploy.sh scripts/server-setup.sh

DB_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
MYSQL_ROOT_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"

if [ ! -f .env ]; then
  cp .env.example .env
fi

if [ ! -f backend/.env ]; then
  cp backend/.env.example backend/.env
fi

# Root compose env (used by docker-compose.prod.yml)
cat > .env <<EOF
APP_NAME=BlogCMS
APP_ENV=production
APP_DEBUG=false
APP_URL=${PUBLIC_URL}

DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=blog
DB_USERNAME=blog_user
DB_PASSWORD=${DB_PASSWORD}
MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

REDIS_HOST=redis
REDIS_PORT=6379

SANCTUM_STATEFUL_DOMAINS=${HOST_NO_SCHEME}
SESSION_DOMAIN=null

VITE_API_URL=/api
EOF

# Sync critical values into Laravel env (APP_KEY is generated by container entrypoint)
python3 - <<'PY'
from pathlib import Path
import re

root = Path("/opt/blog")
# Allow APP_DIR override via env file we just wrote — read values from root .env
vals = {}
for line in (root / ".env").read_text().splitlines():
    if "=" in line and not line.strip().startswith("#"):
        k, v = line.split("=", 1)
        vals[k.strip()] = v.strip()

backend = root / "backend" / ".env"
text = backend.read_text()

def set_key(text, key, value):
    pattern = re.compile(rf"^{re.escape(key)}=.*$", re.M)
    line = f"{key}={value}"
    if pattern.search(text):
        return pattern.sub(line, text)
    return text.rstrip() + "\n" + line + "\n"

for key in [
    "APP_NAME", "APP_ENV", "APP_DEBUG", "APP_URL",
    "DB_CONNECTION", "DB_HOST", "DB_PORT", "DB_DATABASE", "DB_USERNAME", "DB_PASSWORD",
    "REDIS_HOST", "REDIS_PORT", "SANCTUM_STATEFUL_DOMAINS", "SESSION_DOMAIN",
]:
    if key in vals:
        text = set_key(text, key, vals[key])

backend.write_text(text)
print("Updated backend/.env from root .env")
PY

# Deploy key for GitHub Actions (idempotent)
mkdir -p /root/.ssh
if [ ! -f /root/.ssh/blog_deploy ]; then
  ssh-keygen -t ed25519 -f /root/.ssh/blog_deploy -N "" -C "github-actions-blog-deploy"
fi
if ! grep -q "github-actions-blog-deploy" /root/.ssh/authorized_keys 2>/dev/null; then
  cat /root/.ssh/blog_deploy.pub >> /root/.ssh/authorized_keys
fi
chmod 600 /root/.ssh/authorized_keys /root/.ssh/blog_deploy
chmod 644 /root/.ssh/blog_deploy.pub

echo "==> Starting stack"
./scripts/deploy.sh

cat <<EOF

============================================================
Server bootstrap complete.

App URL:     ${PUBLIC_URL}
App path:    ${APP_DIR}
Compose:     docker compose -f docker-compose.yml -f docker-compose.prod.yml

GitHub Actions secrets to set on the repository:
  DEPLOY_HOST   = $(curl -4 -fsS ifconfig.me || hostname -I | awk '{print $1}')
  DEPLOY_USER   = root
  DEPLOY_PORT   = 22
  DEPLOY_PATH   = ${APP_DIR}
  DEPLOY_SSH_KEY = (contents of /root/.ssh/blog_deploy — the PRIVATE key)

Private key path on this server: /root/.ssh/blog_deploy
Public key is already in /root/.ssh/authorized_keys

Admin demo logins are seeded on first boot — change those passwords immediately.
phpMyAdmin is disabled by default. Enable with:
  docker compose -f docker-compose.yml -f docker-compose.prod.yml --profile tools up -d phpmyadmin
============================================================
EOF
